export const ADD_TO_LIST_CHOOSE = 'ADD_TO_LIST_CHOOSE';
export const LOGIN_WITH_THUNK = 'LOGIN_WITH_THUNK';
export const LOGIN_WITH_THUNK_FAILED = 'LOGIN_WITH_THUNK_FAILED';
export const LOGIN_WITH_THUNK_SUCCESS = 'LOGIN_WITH_THUNK_SUCCESS'